const CategoriesTableActionTypes = {
	SET_ORDER_CATEGORIES_START: 'SET_ORDER_CATEGORIES_START',
	SET_ORDER_CATEGORIES_SUCCESS: 'SET_ORDER_CATEGORIES_SUCCESS',
	SET_ORDER_CATEGORIES_FAILURE: 'SET_ORDER_CATEGORIES_FAILURE',

	SET_SELECT_ALL_CATEGORIES_START: 'SET_SELECT_ALL_CATEGORIES_START',
	SET_SELECT_ALL_CATEGORIES_SUCCESS: 'SET_SELECT_ALL_CATEGORIES_SUCCESS',
	SET_SELECT_ALL_CATEGORIES_FAILURE: 'SET_SELECT_ALL_CATEGORIES_FAILURE',

	SET_SELECT_CATEGORIES_START: 'SET_SELECT_CATEGORIES_START',
	SET_SELECT_CATEGORIES_SUCCESS: 'SET_SELECT_CATEGORIES_SUCCESS',
	SET_SELECT_CATEGORIES_FAILURE: 'SET_SELECT_CATEGORIES_FAILURE',

	SET_PAGE_CATEGORIES_START: 'SET_PAGE_CATEGORIES_START',
	SET_PAGE_CATEGORIES_SUCCESS: 'SET_PAGE_CATEGORIES_SUCCESS',
	SET_PAGE_CATEGORIES_FAILURE: 'SET_PAGE_CATEGORIES_FAILURE',

	SET_ROWS_PER_PAGE_CATEGORIES_START: 'SET_ROWS_PER_PAGE_CATEGORIES_START',
	SET_ROWS_PER_PAGE_CATEGORIES_SUCCESS:
		'SET_ROWS_PER_PAGE_CATEGORIES_SUCCESS',
	SET_ROWS_PER_PAGE_CATEGORIES_FAILURE:
		'SET_ROWS_PER_PAGE_CATEGORIES_FAILURE',

	SET_FILTERED_CATEGORIES_START: 'SET_FILTERED_CATEGORIES_START',
	SET_FILTERED_CATEGORIES_SUCCESS: 'SET_FILTERED_CATEGORIES_SUCCESS',
	SET_FILTERED_CATEGORIES_FAILURE: 'SET_FILTERED_CATEGORIES_FAILURE',

	SET_CATEGORIES_SEARCH_FIELD: 'SET_CATEGORIES_SEARCH_FIELD',

	SET_CATEGORIES_ORDER_BY: 'SET_CATEGORIES_ORDER_BY',

	REMOVE_SELECTED_CATEGORIES: 'REMOVE_SELECTED_CATEGORIES',
	REMOVE_CATEGORIES_ORDER_BY: 'REMOVE_CATEGORIES_ORDER_BY',
	REMOVE_CATEGORIES_SEARCH_FIELD: 'REMOVE_CATEGORIES_SEARCH_FIELD',
};

export default CategoriesTableActionTypes;
