const TablesTableActionTypes = {
	SET_ORDER_TABLES_START: 'SET_ORDER_TABLES_START',
	SET_ORDER_TABLES_SUCCESS: 'SET_ORDER_TABLES_SUCCESS',
	SET_ORDER_TABLES_FAILURE: 'SET_ORDER_TABLES_FAILURE',

	SET_SELECT_ALL_TABLES_START: 'SET_SELECT_ALL_TABLES_START',
	SET_SELECT_ALL_TABLES_SUCCESS: 'SET_SELECT_ALL_TABLES_SUCCESS',
	SET_SELECT_ALL_TABLES_FAILURE: 'SET_SELECT_ALL_TABLES_FAILURE',

	SET_SELECT_TABLES_START: 'SET_SELECT_TABLES_START',
	SET_SELECT_TABLES_SUCCESS: 'SET_SELECT_TABLES_SUCCESS',
	SET_SELECT_TABLES_FAILURE: 'SET_SELECT_TABLES_FAILURE',

	SET_PAGE_TABLES_START: 'SET_PAGE_TABLES_START',
	SET_PAGE_TABLES_SUCCESS: 'SET_PAGE_TABLES_SUCCESS',
	SET_PAGE_TABLES_FAILURE: 'SET_PAGE_TABLES_FAILURE',

	SET_ROWS_PER_PAGE_TABLES_START: 'SET_ROWS_PER_PAGE_TABLES_START',
	SET_ROWS_PER_PAGE_TABLES_SUCCESS: 'SET_ROWS_PER_PAGE_TABLES_SUCCESS',
	SET_ROWS_PER_PAGE_TABLES_FAILURE: 'SET_ROWS_PER_PAGE_TABLES_FAILURE',

	SET_FILTERED_TABLES_START: 'SET_FILTERED_TABLES_START',
	SET_FILTERED_TABLES_SUCCESS: 'SET_FILTERED_TABLES_SUCCESS',
	SET_FILTERED_TABLES_FAILURE: 'SET_FILTERED_TABLES_FAILURE',

	SET_TABLES_SEARCH_FIELD: 'SET_TABLES_SEARCH_FIELD',

	SET_TABLES_ORDER_BY: 'SET_TABLES_ORDER_BY',

	REMOVE_SELECTED_TABLES: 'REMOVE_SELECTED_TABLES',
	REMOVE_TABLES_ORDER_BY: 'REMOVE_TABLES_ORDER_BY',
	REMOVE_TABLES_SEARCH_FIELD: 'REMOVE_TABLES_SEARCH_FIELD',

	CLEAR_TABLES_TABLE: 'CLEAR_TABLES_TABLE',
};

export default TablesTableActionTypes;
