const MenusTableActionTypes = {
	SET_ORDER_MENUS_START: 'SET_ORDER_MENUS_START',
	SET_ORDER_MENUS_SUCCESS: 'SET_ORDER_MENUS_SUCCESS',
	SET_ORDER_MENUS_FAILURE: 'SET_ORDER_MENUS_FAILURE',

	SET_SELECT_ALL_MENUS_START: 'SET_SELECT_ALL_MENUS_START',
	SET_SELECT_ALL_MENUS_SUCCESS: 'SET_SELECT_ALL_MENUS_SUCCESS',
	SET_SELECT_ALL_MENUS_FAILURE: 'SET_SELECT_ALL_MENUS_FAILURE',

	SET_SELECT_MENUS_START: 'SET_SELECT_MENUS_START',
	SET_SELECT_MENUS_SUCCESS: 'SET_SELECT_MENUS_SUCCESS',
	SET_SELECT_MENUS_FAILURE: 'SET_SELECT_MENUS_FAILURE',

	SET_PAGE_MENUS_START: 'SET_PAGE_MENUS_START',
	SET_PAGE_MENUS_SUCCESS: 'SET_PAGE_MENUS_SUCCESS',
	SET_PAGE_MENUS_FAILURE: 'SET_PAGE_MENUS_FAILURE',

	SET_ROWS_PER_PAGE_MENUS_START: 'SET_ROWS_PER_PAGE_MENUS_START',
	SET_ROWS_PER_PAGE_MENUS_SUCCESS: 'SET_ROWS_PER_PAGE_MENUS_SUCCESS',
	SET_ROWS_PER_PAGE_MENUS_FAILURE: 'SET_ROWS_PER_PAGE_MENUS_FAILURE',

	SET_FILTERED_MENUS_START: 'SET_FILTERED_MENUS_START',
	SET_FILTERED_MENUS_SUCCESS: 'SET_FILTERED_MENUS_SUCCESS',
	SET_FILTERED_MENUS_FAILURE: 'SET_FILTERED_MENUS_FAILURE',

	SET_MENUS_SEARCH_FIELD: 'SET_MENUS_SEARCH_FIELD',

	SET_MENUS_ORDER_BY: 'SET_MENUS_ORDER_BY',

	REMOVE_SELECTED_MENUS: 'REMOVE_SELECTED_MENUS',
	REMOVE_MENUS_ORDER_BY: 'REMOVE_MENUS_ORDER_BY',
	REMOVE_MENUS_SEARCH_FIELD: 'REMOVE_MENUS_SEARCH_FIELD',

	CLEAR_MENUS_TABLE: 'CLEAR_MENUS_TABLE',
};

export default MenusTableActionTypes;
