const UnitsActionTypes = {
	FETCH_UNITS_START: 'FETCH_UNITS_START',
	FETCH_UNITS_SUCCESS: 'FETCH_UNITS_SUCCESS',
	FETCH_UNITS_FAILURE: 'FETCH_UNITS_FAILURE',

	CLEAR_UNITS_COLLECTIONS: 'CLEAR_UNITS_COLLECTIONS',
};

export default UnitsActionTypes;
