const ItemsActionTypes = {
	FETCH_ITEMS_COLLECTIONS_START: 'FETCH_ITEMS_COLLECTIONS_START',
	FETCH_ITEMS_COLLECTIONS_SUCCESS: 'FETCH_ITEMS_COLLECTIONS_SUCCESS',
	FETCH_ITEMS_COLLECTIONS_UPDATE: 'FETCH_ITEMS_COLLECTIONS_UPDATE',
	FETCH_ITEMS_COLLECTIONS_FAILURE: 'FETCH_ITEMS_COLLECTIONS_FAILURE',

	CONVERT_ITEMS_WITH_USERS_START: 'CONVERT_ITEMS_WITH_USERS_START',
	CONVERT_ITEMS_WITH_USERS_SUCCESS: 'CONVERT_ITEMS_WITH_USERS_SUCCESS',
	CONVERT_ITEMS_WITH_USERS_FAILURE: 'CONVERT_ITEMS_WITH_USERS_FAILURE',

	CLEAR_ITEMS_COLLECTIONS: 'CLEAR_ITEMS_COLLECTIONS',
	REMOVE_ITEMS_COLLECTION_LISTENER: 'REMOVE_ITEMS_COLLECTION_LISTENER',
};

export default ItemsActionTypes;
