const OrdersListActionTypes = {
	FETCH_ORDERS_START: 'FETCH_ORDERS_START',
	FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
	FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',

	SET_ORDER_STATUS: 'SET_ORDER_STATUS',
};

export default OrdersListActionTypes;
