const OrdersListActionTypes = {
	FETCH_ORDERS_START: 'FETCH_ORDERS_START',
	FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
	FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',

	SET_ORDER_STATUS_START: 'SET_ORDER_STATUS_START',
	SET_ORDER_STATUS_SUCCESS: 'SET_ORDER_STATUS_SUCCESS',
	SET_ORDER_STATUS_FAILURE: 'SET_ORDER_STATUS_FAILURE',
};

export default OrdersListActionTypes;
