const ItemDetailActionTypes = {
	FETCH_ITEM_START: 'FETCH_ITEM_START',
	FETCH_ITEM_SUCCESS: 'FETCH_ITEM_SUCCESS',
	FETCH_ITEM_FAILURE: 'FETCH_ITEM_FAILURE',

	SET_ITEM_START: 'SET_ITEM_START',
	SET_ITEM_SUCCESS: 'SET_ITEM_SUCCESS',
	SET_ITEM_FAILURE: 'SET_ITEM_FAILURE',

	CREATE_ITEM_START: 'CREATE_ITEM_START',
	CREATE_ITEM_SUCCESS: 'CREATE_ITEM_SUCCESS',
	CREATE_ITEM_FAILURE: 'CREATE_ITEM_FAILURE',

	UPDATE_ITEM_START: 'UPDATE_ITEM_START',
	UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
	UPDATE_ITEM_FAILURE: 'UPDATE_ITEM_FAILURE',

	REMOVE_ITEM: 'REMOVE_ITEM',
};

export default ItemDetailActionTypes;
