const CategoryDetailActionTypes = {
	FETCH_CATEGORY_START: 'FETCH_CATEGORY_START',
	FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
	FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE',

	SET_CATEGORY_START: 'SET_CATEGORY_START',
	SET_CATEGORY_SUCCESS: 'SET_CATEGORY_SUCCESS',
	SET_CATEGORY_FAILURE: 'SET_CATEGORY_FAILURE',

	CREATE_CATEGORY_START: 'CREATE_CATEGORY_START',
	CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
	CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',

	UPDATE_CATEGORY_START: 'UPDATE_CATEGORY_START',
	UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
	UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE',

	DELETE_CATEGORY_START: 'DELETE_CATEGORY_START',
	DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
	DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE',

	DELETE_MULTIPLE_CATEGORIES_START: 'DELETE_MULTIPLE_CATEGORIES_START',
	DELETE_MULTIPLE_CATEGORIES_SUCCESS: 'DELETE_MULTIPLE_CATEGORIES_SUCCESS',
	DELETE_MULTIPLE_CATEGORIES_FAILURE: 'DELETE_MULTIPLE_CATEGORIES_FAILURE',

	IS_NEW_CATEGORY: 'IS_NEW_CATEGORY',

	INPUT_CATEGORY_FAILURE: 'INPUT_CATEGORY_FAILURE',

	REMOVE_CATEGORY: 'REMOVE_CATEGORY',
};

export default CategoryDetailActionTypes;
