const MenuDetailActionTypes = {
	FETCH_MENU_START: 'FETCH_MENU_START',
	FETCH_MENU_SUCCESS: 'FETCH_MENU_SUCCESS',
	FETCH_MENU_FAILURE: 'FETCH_MENU_FAILURE',

	SET_MENU_START: 'SET_MENU_START',
	SET_MENU_SUCCESS: 'SET_MENU_SUCCESS',
	SET_MENU_FAILURE: 'SET_MENU_FAILURE',

	CREATE_MENU_START: 'CREATE_MENU_START',
	CREATE_MENU_SUCCESS: 'CREATE_MENU_SUCCESS',
	CREATE_MENU_FAILURE: 'CREATE_MENU_FAILURE',

	UPDATE_MENU_START: 'UPDATE_MENU_START',
	UPDATE_MENU_SUCCESS: 'UPDATE_MENU_SUCCESS',
	UPDATE_MENU_FAILURE: 'UPDATE_MENU_FAILURE',

	DELETE_MENU_START: 'DELETE_MENU_START',
	DELETE_MENU_SUCCESS: 'DELETE_MENU_SUCCESS',
	DELETE_MENU_FAILURE: 'DELETE_MENU_FAILURE',

	DELETE_MULTIPLE_MENUS_START: 'DELETE_MULTIPLE_MENUS_START',
	DELETE_MULTIPLE_MENUS_SUCCESS: 'DELETE_MULTIPLE_MENUS_SUCCESS',
	DELETE_MULTIPLE_MENUS_FAILURE: 'DELETE_MULTIPLE_MENUS_FAILURE',

	IS_NEW_MENU: 'IS_NEW_MENU',

	INPUT_MENU_FAILURE: 'INPUT_MENU_FAILURE',

	REMOVE_MENU: 'REMOVE_MENU',
};

export default MenuDetailActionTypes;
