const OrderFormActionTypes = {
	SELECT_MENU_START: 'SELECT_MENU_START',
	SELECT_MENU_SUCCESS: 'SELECT_MENU_SUCCESS',
	SELECT_MENU_FAILURE: 'SELECT_MENU_FAILURE',

	SET_CATEGORY_ORDER_FORM: 'SET_CATEGORY_ORDER_FORM',

	SET_EXTRA_MENU_ITEM_START: 'SET_EXTRA_MENU_ITEM_START',

	REMOVE_ORDER_FORM: 'REMOVE_ORDER_FORM',
};

export default OrderFormActionTypes;
