const OrderFormActionTypes = {
	SELECT_MENU_START: 'SELECT_MENU_START',
	SELECT_MENU_SUCCESS: 'SELECT_MENU_SUCCESS',
	SELECT_MENU_FAILURE: 'SELECT_MENU_FAILURE',

	SET_EXTRA_MENU_ITEM_START: 'SET_EXTRA_MENU_ITEM_START',
	SET_EXTRA_MENU_ITEM_SUCCESS: 'SET_EXTRA_MENU_ITEM_SUCCESS',
	SET_EXTRA_MENU_ITEM_FAILURE: 'SET_EXTRA_MENU_ITEM_FAILURE',

	SET_CATEGORY_ORDER_FORM: 'SET_CATEGORY_ORDER_FORM',

	REMOVE_ORDER_ITEM_START: 'REMOVE_ORDER_ITEM_START',
	REMOVE_ORDER_ITEM_SUCCESS: 'REMOVE_ORDER_ITEM_SUCCESS',
	REMOVE_ORDER_ITEM_FAILURE: 'REMOVE_ORDER_ITEM_FAILURE',

	CLEAR_ORDER_FORM: 'CLEAR_ORDER_FORM',

	CLEAR_CATEGORY_FILTER: 'CLEAR_CATEGORY_FILTER',
};

export default OrderFormActionTypes;
