const TablesActionTypes = {
	FETCH_TABLES_COLLECTIONS_START: 'FETCH_TABLES_COLLECTIONS_START',
	FETCH_TABLES_COLLECTIONS_SUCCESS: 'FETCH_TABLES_COLLECTIONS_SUCCESS',
	FETCH_TABLES_COLLECTIONS_UPDATE: 'FETCH_TABLES_COLLECTIONS_UPDATE',
	FETCH_TABLES_COLLECTIONS_FAILURE: 'FETCH_TABLES_COLLECTIONS_FAILURE',

	CLEAR_TABLES_COLLECTIONS: 'CLEAR_TABLES_COLLECTIONS',

	REMOVE_TABLES_COLLECTION_LISTENER: 'REMOVE_TABLES_COLLECTION_LISTENER',
};

export default TablesActionTypes;
