const TableDetailActionTypes = {
	FETCH_TABLE_START: 'FETCH_TABLE_START',
	FETCH_TABLE_SUCCESS: 'FETCH_TABLE_SUCCESS',
	FETCH_TABLE_FAILURE: 'FETCH_TABLE_FAILURE',

	SET_TABLE_START: 'SET_TABLE_START',
	SET_TABLE_SUCCESS: 'SET_TABLE_SUCCESS',
	SET_TABLE_FAILURE: 'SET_TABLE_FAILURE',

	CREATE_TABLE_START: 'CREATE_TABLE_START',
	CREATE_TABLE_SUCCESS: 'CREATE_TABLE_SUCCESS',
	CREATE_TABLE_FAILURE: 'CREATE_TABLE_FAILURE',

	UPDATE_TABLE_START: 'UPDATE_TABLE_START',
	UPDATE_TABLE_SUCCESS: 'UPDATE_TABLE_SUCCESS',
	UPDATE_TABLE_FAILURE: 'UPDATE_TABLE_FAILURE',

	DELETE_TABLE_START: 'DELETE_TABLE_START',
	DELETE_TABLE_SUCCESS: 'DELETE_TABLE_SUCCESS',
	DELETE_TABLE_FAILURE: 'DELETE_TABLE_FAILURE',

	DELETE_MULTIPLE_TABLES_START: 'DELETE_MULTIPLE_TABLES_START',
	DELETE_MULTIPLE_TABLES_SUCCESS: 'DELETE_MULTIPLE_TABLES_SUCCESS',
	DELETE_MULTIPLE_TABLES_FAILURE: 'DELETE_MULTIPLE_TABLES_FAILURE',

	IS_NEW_TABLE: 'IS_NEW_TABLE',

	INPUT_TABLE_FAILURE: 'INPUT_TABLE_FAILURE',

	REMOVE_TABLE: 'REMOVE_TABLE',
};

export default TableDetailActionTypes;
