const CategoriesActionTypes = {
	FETCH_CATEGORIES_COLLECTIONS_START: 'FETCH_CATEGORIES_COLLECTIONS_START',
	FETCH_CATEGORIES_COLLECTIONS_SUCCESS:
		'FETCH_CATEGORIES_COLLECTIONS_SUCCESS',
	FETCH_CATEGORIES_COLLECTIONS_UPDATE: 'FETCH_CATEGORIES_COLLECTIONS_UPDATE',
	FETCH_CATEGORIES_COLLECTIONS_FAILURE:
		'FETCH_CATEGORIES_COLLECTIONS_FAILURE',

	CLEAR_CATEGORIES_COLLECTIONS: 'CLEAR_CATEGORIES_COLLECTIONS',

	REMOVE_CATEGORIES_COLLECTION_LISTENER:
		'REMOVE_CATEGORIES_COLLECTION_LISTENER',
};

export default CategoriesActionTypes;
