const UsersActionTypes = {
	GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
	SIGN_IN_SUCCUSS: 'SIGN_IN_SUCCUSS',
	SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
	SIGN_OUT_START: 'SIGN_OUT_START',
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
	SIGN_UP_START: 'SIGN_UP_START',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
	FETCH_ALL_USERS_START: 'FETCH_ALL_USERS_START',
	FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
	FETCH_ALL_USERS_UPDATE: 'FETCH_ALL_USERS_UPDATE',
	FETCH_ALL_USERS_FAILURE: 'FETCH_ALL_USERS_FAILURE',
	REMOVE_USER_LISTENER: 'REMOVE_USER_LISTENER',
	AUTH_LISTENER_START: 'AUTH_LISTENER_START',
	AUTH_LISTENER_FAILURE: 'AUTH_LISTENER_FAILURE',
};

export default UsersActionTypes;
