const UsersActionTypes = {
	GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',

	SIGN_IN_SUCCUSS: 'SIGN_IN_SUCCUSS',
	SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

	SIGN_OUT_START: 'SIGN_OUT_START',
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

	SIGN_UP_START: 'SIGN_UP_START',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

	FETCH_ALL_USERS_START: 'FETCH_ALL_USERS_START',
	FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
	FETCH_ALL_USERS_UPDATE: 'FETCH_ALL_USERS_UPDATE',
	FETCH_ALL_USERS_FAILURE: 'FETCH_ALL_USERS_FAILURE',

	AUTH_LISTENER_START: 'AUTH_LISTENER_START',
	AUTH_LISTENER_FAILURE: 'AUTH_LISTENER_FAILURE',
	REMOVE_USERS_LISTENER: 'REMOVE_USERS_LISTENER',

	SET_USER_CREDENTIALS: 'SET_USER_CREDENTIALS',

	SET_INPUT_ERRORS: 'SET_INPUT_ERRORS',

	CLEAR_INPUT_ERRORS: 'CLEAR_INPUT_ERRORS',
};

export default UsersActionTypes;
