const OrdersTableActionTypes = {
	SET_ORDERS_ORDER_START: 'SET_ORDERS_ORDER_START',
	SET_ORDERS_ORDER_SUCCESS: 'SET_ORDERS_ORDER_SUCCESS',
	SET_ORDERS_ORDER_FAILURE: 'SET_ORDERS_ORDER_FAILURE',

	SET_ORDERS_PAGE_START: 'SET_ORDERS_PAGE_START',
	SET_ORDERS_PAGE_SUCCESS: 'SET_ORDERS_PAGE_SUCCESS',
	SET_ORDERS_PAGE_FAILURE: 'SET_ORDERS_PAGE_FAILURE',

	SET_ORDERS_ROWS_PER_PAGE_START: 'SET_ORDERS_ROWS_PER_PAGE_START',
	SET_ORDERS_ROWS_PER_PAGE_SUCCESS: 'SET_ORDERS_ROWS_PER_PAGE_SUCCESS',
	SET_ORDERS_ROWS_PER_PAGE_FAILURE: 'SET_ORDERS_ROWS_PER_PAGE_FAILURE',

	SET_ORDERS_ORDER_BY: 'SET_ORDERS_ORDER_BY',
};

export default OrdersTableActionTypes;
