const OrdersActionTypes = {
	FETCH_ORDERS_COLLECTIONS_START: 'FETCH_ORDERS_COLLECTIONS_START',
	FETCH_ORDERS_COLLECTIONS_SUCCESS: 'FETCH_ORDERS_COLLECTIONS_SUCCESS',
	FETCH_ORDERS_COLLECTIONS_UPDATE: 'FETCH_ORDERS_COLLECTIONS_UPDATE',
	FETCH_ORDERS_COLLECTIONS_FAILURE: 'FETCH_ORDERS_COLLECTIONS_FAILURE',

	CLEAR_ORDERS_COLLECTIONS: 'CLEAR_ORDERS_COLLECTIONS',
	REMOVE_ORDERS_COLLECTION_LISTENER: 'REMOVE_ORDERS_COLLECTION_LISTENER',
};

export default OrdersActionTypes;
