const ItemsTableActionTypes = {
	SET_ORDER_START: 'SET_ORDER_START',
	SET_ORDER_SUCCESS: 'SET_ORDER_SUCCESS',
	SET_ORDER_FAILURE: 'SET_ORDER_FAILURE',

	SET_ORDER_BY_START: 'SET_ORDER_BY_START',
	SET_ORDER_BY_SUCCESS: 'SET_ORDER_BY_SUCCESS',

	SET_SELECT_ALL_START: 'SET_SELECT_ALL_START',
	SET_SELECT_ALL_SUCCESS: 'SET_SELECT_ALL_SUCCESS',
	SET_SELECT_ALL_FAILURE: 'SET_SELECT_ALL_FAILURE',

	SET_SELECT_START: 'SET_SELECT_START',
	SET_SELECT_SUCCESS: 'SET_SELECT_SUCCESS',
	SET_SELECT_FAILURE: 'SET_SELECT_FAILURE',

	SET_PAGE_START: 'SET_PAGE_START',
	SET_PAGE_SUCCESS: 'SET_PAGE_SUCCESS',
	SET_PAGE_FAILURE: 'SET_PAGE_FAILURE',

	SET_ROWS_PER_PAGE_START: 'SET_ROWS_PER_PAGE_START',
	SET_ROWS_PER_PAGE_SUCCESS: 'SET_ROWS_PER_PAGE_SUCCESS',
	SET_ROWS_PER_PAGE_FAILURE: 'SET_ROWS_PER_PAGE_FAILURE',

	REMOVE_SELECTED: 'REMOVE_SELECTED',
};

export default ItemsTableActionTypes;
