const ItemsTableActionTypes = {
	SET_ORDER_ITEMS_START: 'SET_ORDER_ITEMS_START',
	SET_ORDER_ITEMS_SUCCESS: 'SET_ORDER_ITEMS_SUCCESS',
	SET_ORDER_ITEMS_FAILURE: 'SET_ORDER_ITEMS_FAILURE',

	SET_SELECT_ALL_ITEMS_START: 'SET_SELECT_ALL_ITEMS_START',
	SET_SELECT_ALL_ITEMS_SUCCESS: 'SET_SELECT_ALL_ITEMS_SUCCESS',
	SET_SELECT_ALL_ITEMS_FAILURE: 'SET_SELECT_ALL_ITEMS_FAILURE',

	SET_SELECT_ITEMS_START: 'SET_SELECT_ITEMS_START',
	SET_SELECT_ITEMS_SUCCESS: 'SET_SELECT_ITEMS_SUCCESS',
	SET_SELECT_ITEMS_FAILURE: 'SET_SELECT_ITEMS_FAILURE',

	SET_PAGE_ITEMS_START: 'SET_PAGE_ITEMS_START',
	SET_PAGE_ITEMS_SUCCESS: 'SET_PAGE_ITEMS_SUCCESS',
	SET_PAGE_ITEMS_FAILURE: 'SET_PAGE_ITEMS_FAILURE',

	SET_ROWS_PER_PAGE_ITEMS_START: 'SET_ROWS_PER_PAGE_ITEMS_START',
	SET_ROWS_PER_PAGE_ITEMS_SUCCESS: 'SET_ROWS_PER_PAGE_ITEMS_SUCCESS',
	SET_ROWS_PER_PAGE_ITEMS_FAILURE: 'SET_ROWS_PER_PAGE_ITEMS_FAILURE',

	SET_FILTERED_ITEMS_START: 'SET_FILTERED_ITEMS_START',
	SET_FILTERED_ITEMS_SUCCESS: 'SET_FILTERED_ITEMS_SUCCESS',
	SET_FILTERED_ITEMS_FAILURE: 'SET_FILTERED_ITEMS_FAILURE',

	SET_ITEMS_SEARCH_FIELD: 'SET_ITEMS_SEARCH_FIELD',

	SET_ITEMS_ORDER_BY: 'SET_ITEMS_ORDER_BY',

	REMOVE_SELECTED_ITEMS: 'REMOVE_SELECTED_ITEMS',
	REMOVE_ITEMS_ORDER_BY: 'REMOVE_ITEMS_ORDER_BY',
	REMOVE_ITEMS_SEARCH_FIELD: 'REMOVE_ITEMS_SEARCH_FIELD',

	CLEAR_ITEMS_TABLE: 'CLEAR_ITEMS_TABLE',
};

export default ItemsTableActionTypes;
