const ItemsTableActionTypes = {
	SET_ORDER_START: 'SET_ORDER_START',
	SET_ORDER_SUCCESS: 'SET_ORDER_SUCCESS',
	SET_ORDER_FAILURE: 'SET_ORDER_FAILURE',

	SET_ORDER_BY_START: 'SET_ORDER_BY_START',
	SET_ORDER_BY_SUCCESS: 'SET_ORDER_BY_SUCCESS',
	SET_ORDER_BY_FAILURE: 'SET_ORDER_BY_FAILURE',

	SET_SELECT_ALL_START: 'SET_SELECT_ALL_START',
	SET_SELECT_ALL_SUCCESS: 'SET_SELECT_ALL_SUCCESS',
	SET_SELECT_ALL_FAILURE: 'SET_SELECT_ALL_FAILURE',
};

export default ItemsTableActionTypes;
